
name: Trending Projects Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trend-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install lru-cache@7.10.6 glob@9 puppeteer

      - name: Scrape trending projects from GitHub
        run: |
          npx puppeteer --headed \
            https://github.com/trending > trending-projects.html

      - name: Generate pretty HTML report (using 
