name: Trending Projects Report

on:
  push:
    branches:
      - main

jobs:
  trend-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install gh-pages puppeteer

      - name: Login to GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node login.js

      - name: Scrape trending projects from GitHub
        run: |
          npx puppeteer --headed \
            --extra-options="--window-size=1200,800" \
            https://github.com/trending > trending-projects.html

      - name: Generate pretty HTML report
        run: |
          npx html-puppeteer-prettier \
            trending-projects.html > trending-report.html

      - name: Upload artifact as HTML report
        uses: actions/upload-artifact@v2
        with:
          name: trending-report.html
          path: trending-report.html

      - name: Deploy to gh-pages (optional)
        if: github.event_name == 'push' && github.workflow == 'trend-report'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install gh-pages
          npx gh-pages -d ./
