
name: Trending Projects Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install cheerio axios

      - name: Scrape trending projects
        run: |
          const axios = require('axios');
          const cheerio = require('cheerio');

          async function scrapeTrendingProjects() {
            try {
              const response = await axios.get('https://github.com/trending?since=daily');
              const $ = cheerio.load(response.data);
              const projects = [];

              $('.Box-row').each((index, element) => {
                const title = $(element).find('.h3').text().trim();
                const description = $(element).find('.py-1').text().trim();
                const link = $(element).find('a').attr('href');
                projects.push({ title, description, link });
              });

              return projects;
            } catch (error) {
              console.error(error);
            }
          }

          scrapeTrendingProjects()
            .then((projects) => {
              const html = generateHtmlReport(projects);
              fs.writeFileSync('report.html', html);
            })
            .catch((error) => {
              console.error(error);
            });

      - name: Generate HTML report
        run: |
          function generateHtmlReport(projects) {
            return `
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Trending Projects Report</title>
                <style>
                  body {
                    font-family: Arial, sans-serif;
                  }
                  .container {
                    max-width: 800px;
                    margin: 40px auto;
                    padding: 20px;
                    background-color: #f9f9f9;
                    border: 1px solid #ddd;
                    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
                  }
                  .project {
                    margin-bottom: 20px;
                  }
                  .project-title {
                    font-weight: bold;
                  }
                  .project-description {
                    color: #666;
                  }
                </style>
              </head>
              <body>
                <div class="container">
                  <h1>Trending Projects Report</h1>
                  ${projects.map((project) => `
                    <div class="project">
                      <h2 class="project-title"><a href="${project.link}" target="_blank">${project.title}</a></h2>
                      <p class="project-description">${project.description}</p>
                    </div>
                  `).join('')}
                </div>
              </body>
              </html>
            `;
          }

      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: trending-projects-report
          path: report.html

      - name: Display report
        run: |
          echo "Report uploaded! You can view it here:"
          echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/artifacts/trending-projects-report/report.html"
