name: Scrape GitHub Trending Projects

on:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Scrape GitHub Trending Projects
        run: python scrape_github_trending.py

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: github-trending-report
          path: report.html
          retention-days: 1
